### ISSUE TITLE
「錢」點解有zin2呢個讀音？

### ISSUE THREAD

**Issue by AlienKevin** [sgalal/to-jyutping#4]
\>\>\> ToJyutping.get_jyutping_text("錢")
'**zin2**'

\>\>\> ToJyutping.get_jyutping_text("你嘅錢")
'nei5 ge3 **zin2**'

其他時候又係正確嘅：
\>\>\> ToJyutping.get_jyutping_text("有錢")
'jau5 cin2'
\>\>\> ToJyutping.get_jyutping_text("冇錢")
'mou5 cin2'

**Comment by graphemecluster** [comment]
Fixed in 0.3.0.
